# Generated by Django 4.2.6 on 2023-10-28 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_anthology'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publishing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.publishing', verbose_name='Publishing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='anthology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='catalog.anthology', verbose_name='Anthology'),
            preserve_default=False,
        ),
    ]
