# Generated by Django 4.2.6 on 2023-10-28 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_author_publishing_genre_anthology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='publishing',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='anthology',
        ),
    ]
