# Generated by Django 4.2.6 on 2023-11-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_author_publishing_remove_genre_anthology_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, to='catalog.author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, to='catalog.genre', verbose_name='Genre'),
        ),
    ]
