# Generated by Django 4.2.6 on 2023-11-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_book_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.TextField(default='Cardboard', verbose_name='Binding'),
        ),
    ]
