# Generated by Django 4.2.6 on 2023-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_book_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(default='0x0', max_length=50, verbose_name='Format book'),
        ),
    ]
