# Generated by Django 4.2.6 on 2023-11-05 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_book_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=1000000000000, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(13)], verbose_name='ISBN 13 number'),
        ),
    ]
