# Generated by Django 4.2.6 on 2023-11-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_book_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age',
            field=models.CharField(default='0+', max_length=4, verbose_name='Age limit'),
        ),
    ]
