# Generated by Django 4.2.6 on 2023-11-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding',
            field=models.CharField(default='Cardboard', max_length=50, verbose_name='Binding'),
        ),
    ]
