# Generated by Django 4.2.6 on 2023-11-05 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_book_date_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_catalog',
        ),
        migrations.AddField(
            model_name='book',
            name='date_change',
            field=models.DateField(default=datetime.date.today, verbose_name='date of last change'),
        ),
    ]
