# Generated by Django 4.2.6 on 2023-11-05 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_remove_book_date_catalog_book_date_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of catalogin'),
        ),
    ]
