# Generated by Django 4.2.6 on 2023-11-05 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(default=1000000000000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='ISBN 13 number'),
        ),
    ]
