# Generated by Django 4.2.6 on 2023-11-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='anthology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.anthology', verbose_name='Anthology'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, default='No author', to='catalog.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(blank=True, default='No genre', to='catalog.genre', verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Book name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Price BYN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='catalog.publishing', verbose_name='Publishing'),
        ),
    ]
