# Generated by Django 4.2.6 on 2023-11-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0027_alter_book_anthology_alter_book_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Order summ')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.book', verbose_name='Book')),
                ('order_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.book', verbose_name='Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
