# Generated by Django 4.2.6 on 2023-11-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='BYN', max_length=3, verbose_name='Currency'),
        ),
    ]
