# Generated by Django 4.2.6 on 2023-11-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
    ]
