# Generated by Django 4.2.6 on 2023-11-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_book_author_alter_book_genre_alter_book_name'),
        ('basket', '0005_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='basket.cart', verbose_name='Cart')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='catalog.book', verbose_name='Good')),
            ],
        ),
    ]
